group: citybench_test_part2
task:
# - citybench_attribute_comparison_test
# - citybench_visual_prompt_reasoning_test
# - citybench_city_retrieval_test
- citybench_attribute_recognition_test
- citybench_ground_object_recognition_test
- citybench_counting_test
# - citybench_image_retrieval_test
# - citybench_localization_test
# - citybench_orientation_test
# - citybench_role_based_reasoning_test
# - citybench_traffic_sign_reasoning_test
# - citybench_road_understanding_test